/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PokemonType } from '../models/pokemon-type';
export interface Move {
  accuracy?: number;
  category?: 'NON_DAMAGING' | 'SPECIAL' | 'PHYSICAL';
  description?: string;
  name?: string;
  power?: number;
  pp?: number;
  type?: PokemonType;
}
