/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Pokemon } from '../models/pokemon';
export interface PokemonListResponse {
  pokemonList?: Array<Pokemon>;
}
