/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PokemonType } from '../models/pokemon-type';
export interface Pokemon {
  ability?: {
'first'?: string;
'second'?: string;
'hidden'?: string;
};
  baseStatistics?: {
'hp'?: number;
'attack'?: number;
'defense'?: number;
'specialAttack'?: number;
'specialDefense'?: number;
'speed'?: number;
};
  description?: string;
  entryNumber?: number;
  evolutionStageEntry?: {
'previous'?: number;
'next'?: number;
};
  height?: string;
  moves?: Array<string>;
  name?: string;
  sprites?: Array<{
'frontDefaultBig'?: string;
'frontDefaultMedium'?: string;
'frontDefaultSmall'?: string;
}>;
  types?: Array<PokemonType>;

  /**
   * If the pokemon is in evolved form, what are the requirements to make it evolve to its present stage
   */
  wayToEvolvedStage?: string;
  weight?: string;
}
