version: '3.8'

services:
  java-app:
    container_name: "java-app"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    container_name: "mongodb"
    ports:
      - "27017:27017"