/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Move } from './models/move';
export type { Pokemon } from './models/pokemon';
export { PokemonType } from './models/pokemon-type';
