/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { PokemonService } from './services/pokemon.service';
export { MoveService } from './services/move.service';
