/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Move } from '../../models/move';
import { Pokemon } from '../../models/pokemon';

export interface GetPokemon$Params {

/**
 * Entry number of the Pokemon to delete
 */
  entryNumber: number;
}

export function getPokemon(http: HttpClient, rootUrl: string, params: GetPokemon$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'pokemon'?: Pokemon;
'moves'?: Array<Move>;
'evolutions'?: Array<Pokemon>;
}>> {
  const rb = new RequestBuilder(rootUrl, getPokemon.PATH, 'get');
  if (params) {
    rb.path('entryNumber', params.entryNumber, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'pokemon'?: Pokemon;
      'moves'?: Array<Move>;
      'evolutions'?: Array<Pokemon>;
      }>;
    })
  );
}

getPokemon.PATH = '/v1/pokedex/pokemon/{entryNumber}';
