/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PokemonListResponse } from '../../models/pokemon-list-response';

export interface PostPokemonSearch$Params {
      body?: {
'name'?: string;
}
}

export function postPokemonSearch(http: HttpClient, rootUrl: string, params?: PostPokemonSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<PokemonListResponse>> {
  const rb = new RequestBuilder(rootUrl, postPokemonSearch.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PokemonListResponse>;
    })
  );
}

postPokemonSearch.PATH = '/v1/pokedex/pokemon/search';
