/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pokemon } from '../../models/pokemon';

export interface PostPokemonCreate$Params {
  
    /**
     * Pokemon object that needs to be added
     */
    body?: Pokemon
}

export function postPokemonCreate(http: HttpClient, rootUrl: string, params?: PostPokemonCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<Pokemon>> {
  const rb = new RequestBuilder(rootUrl, postPokemonCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Pokemon>;
    })
  );
}

postPokemonCreate.PATH = '/pokedex/pokemon';
