/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MoveListResponse } from '../../models/move-list-response';

export interface PostMoveSearch$Params {
  
    /**
     * String containing the names
     */
    body?: {
'names'?: Array<string>;
}
}

export function postMoveSearch(http: HttpClient, rootUrl: string, params?: PostMoveSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<MoveListResponse>> {
  const rb = new RequestBuilder(rootUrl, postMoveSearch.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MoveListResponse>;
    })
  );
}

postMoveSearch.PATH = '/v1/pokedex/move/search';
