openapi: 3.0.1
info:
  title: User API
  version: 1.0.0
  description: API for the Pokedex
paths:
  /v1/pokedex/pokemon:
    get:
      tags:
        - Pokemon
      summary: Get all pokemon
      description: Get all pokemon from the db, using a pagination. The default limit of pokemon per page is 50
      operationId: get-all-pokemon
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: The number of pokemon to skip before starting to collect the result set
        - in: query
          name: limit
          schema:
            type: integer
          description: The numbers of pokemon to return
      responses:
        '200':
          description: Pokemon fetched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PokemonListResponse'
    post:
      tags:
        - Pokemon
      summary: Create a new pokemon
      description: Add a new pokemon to the db.
      operationId: post-pokemon-create
      requestBody:
        description: Pokemon object that needs to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pokemon'
      responses:
        '201':
          description: Pokemon created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pokemon'
        '400':
          description: Invalid input
  /v1/pokedex/pokemon/{entryNumber}:
    get:
      tags:
        - Pokemon
      summary: Get a specific pokemon and its related resources
      operationId: get-pokemon
      parameters:
        - name: entryNumber
          in: path
          required: true
          description: Entry number of the Pokemon to delete
          schema:
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  pokemon:
                    $ref: '#/components/schemas/Pokemon'
                  moves:
                    type: array
                    items:
                      $ref: '#/components/schemas/Move'
                  evolutions:
                    type: array
                    items:
                      $ref: '#/components/schemas/Pokemon'
    delete:
      tags:
        - Pokemon
      summary: Delete a pokemon knowing its entryNumber
      operationId: delete-pokemon
      parameters:
        - name: entryNumber
          in: path
          required: true
          description: Entry number of the Pokemon to delete
          schema:
            type: integer
      responses:
        '204':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Entry deleted successfully
  /v1/pokedex/pokemon/search:
    post:
      tags:
        - Pokemon
      summary: Create a Pokemon by its name
      description: Search a Pokemon
      operationId: post-pokemon-search
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Pokemon found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PokemonListResponse'
  /v1/pokedex/move:
    post:
      tags:
        - Move
      summary: Create a new move
      description: Add a new move to the db.
      operationId: post-move-create
      requestBody:
        description: Move object that needs to be added
        content:
          application/json:
            schema:
              type: object
              properties:
                move:
                  $ref: '#/components/schemas/Move'
      responses:
        '201':
          description: Move created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoveResponse'
        '400':
          description: Invalid input
  /v1/pokedex/move/search:
    post:
      tags:
        - Move
      summary: Search moves
      description: Search moves (by names) from the db.
      operationId: post-move-search
      requestBody:
        description: String containing the names
        content:
          application/json:
            schema:
              type: object
              properties:
                names:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Move found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoveListResponse'
        '400':
          description: Invalid input
components:
  schemas:
    MoveResponse:
      title: 'MoveResponse'
      type: object
      properties:
        move:
          $ref: '#/components/schemas/Move'
    MoveListResponse:
      title: 'MoveListResponse'
      type: object
      properties:
        moveList:
          type: array
          items:
            $ref: '#/components/schemas/Move'
    PokemonListResponse:
      title: 'PokemonListResponse'
      type: object
      properties:
        pokemonList:
          type: array
          items:
            $ref: '#/components/schemas/Pokemon'
    Move:
      type: object
      properties:
        name:
          type: string
          required: true
        description:
          type: string
          required: true
        type:
          $ref: '#/components/schemas/PokemonType'
          required: true
        power:
          type: integer
        accuracy:
          type: integer
        pp:
          type: integer
          required: true
        category:
          type: string
          required: true
          enum:
            - NON_DAMAGING
            - SPECIAL
            - PHYSICAL
    PokemonType:
      type: string
      enum:
        - Normal
        - Fire
        - Water
        - Grass
        - Electric
        - Ice
        - Fighting
        - Poison
        - Ground
        - Flying
        - Psychic
        - Bug
        - Rock
        - Ghost
        - Dragon
        - Dark
        - Steel
        - Fairy
    Pokemon:
      type: object
      properties:
        entryNumber:
          type: integer
          required: true
        name:
          type: string
          required: true
        description:
          type: string
        height:
          type: string
        weight:
          type: string
        sprite:
          title: 'PokemonSprite'
          type: object
          properties:
            frontDefaultBig:
              type: string
            frontDefaultMedium:
              type: string
            frontDefaultSmall:
              type: string
        types:
          type: array
          items:
            $ref: '#/components/schemas/PokemonType'
        ability:
          type: object
          properties:
            first:
              type: string
            second:
              type: string
            hidden:
              type: string
        baseStatistics:
          title: 'PokemonBaseStatistic'
          type: object
          properties:
            hp:
              type: integer
            attack:
              type: integer
            defense:
              type: integer
            specialAttack:
              type: integer
            specialDefense:
              type: integer
            speed:
              type: integer
        evolutionStageEntry:
          type: object
          properties:
            previous:
              type: integer
            next:
              type: array
              items:
                type: integer
        wayToEvolvedStage:
          type: string
          description: 'If the pokemon is in evolved form, what are the requirements to make it evolve to its present stage'
        moves:
          type: array
          items:
            type: string
