openapi: 3.0.1
info:
  title: User API
  version: 1.0.0
  description: API for the Pokedex
paths:
  /pokedex/pokemon:
    get:
      tags:
        - Pokemon
      summary: Get all pokemon
      description: Get all pokemon from the db, using a pagination. The default limit of pokemon per page is 50
      operationId: get-all-pokemon
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: The number of pokemon to skip before starting to collect the result set
        - in: query
          name: limit
          schema:
            type: integer
          description: The numbers of pokemon to return
      responses:
        '200':
          description: Pokemon fetched successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pokemon'
    post:
      tags:
        - Pokemon
      summary: Create a new pokemon
      description: Add a new pokemon to the db.
      operationId: post-pokemon-create
      requestBody:
        description: Pokemon object that needs to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pokemon'
      responses:
        '201':
          description: Pokemon created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pokemon'
        '400':
          description: Invalid input
  /pokedex/pokemon/{entryNumber}:
    delete:
      tags:
        - Pokemon
      summary: Delete a pokemon knowing its entryNumber
      operationId: delete-pokemon
      parameters:
        - name: entryNumber
          in: path
          required: true
          description: Entry number of the Pokemon to delete
          schema:
            type: integer
      responses:
        '204':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Entry deleted successfully
components:
  schemas:
    PokemonType:
      type: string
      enum:
        - Normal
        - Fire
        - Water
        - Grass
        - Electric
        - Ice
        - Fighting
        - Poison
        - Ground
        - Flying
        - Psychic
        - Bug
        - Rock
        - Ghost
        - Dragon
        - Dark
        - Steel
        - Fairy
    Pokemon:
      type: object
      properties:
        entryNumber:
          type: integer
          required: true
        name:
          type: string
          required: true
        description:
          type: string
        height:
          type: string
        weight:
          type: string
        sprites:
          type: array
          items:
            title: 'PokemonSprite'
            type: object
            properties:
              frontDefaultBig:
                type: string
              frontDefaultMedium:
                type: string
              frontDefaultSmall:
                type: string
        types:
          type: array
          items:
            $ref: '#/components/schemas/PokemonType'
        ability:
          type: object
          properties:
            first:
              type: string
            second:
              type: string
            hidden:
              type: string
        baseStatistics:
          title: 'PokemonBaseStatistic'
          type: object
          properties:
            hp:
              type: integer
            attack:
              type: integer
            defense:
              type: integer
            specialAttack:
              type: integer
            specialDefense:
              type: integer
            speed:
              type: integer
        evolutionStageEntry:
          type: object
          properties:
            previous:
              type: integer
            next:
              type: integer
        wayToEvolvedStage:
          type: string
          description: 'If the pokemon is in evolved form, what are the requirements to make it evolve to its present stage'
        moves:
          type: array
          items:
            title: 'Move'
            type: object
            properties:
              name:
                type: string
                required: true
              type:
                $ref: '#/components/schemas/PokemonType'
                required: true
              wayToLearn:
                type: string